[package]
name = "minimal-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "minimal"
path = "src/main.rs"

[dependencies]
rustio-admin = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
