//! Generated by `rustio-admin startapp address`. Customise freely.

use rustio_admin::{ModelAdmin, RustioAdmin};

// `Address` pluralises irregularly: the auto slug is `address`, but the
// table is `addresses`. `#[rustio(table = "…")]` pins the SQL table name
// without changing the admin URL slug.
#[derive(RustioAdmin)]
#[rustio(table = "addresses")]
pub struct Address {
    pub id: i64,
    pub customer_id: i64,
    pub recipient_name: String,
    pub line1: String,
    pub line2: String,
    pub city: String,
    pub postal_code: String,
    pub country: String,
    pub is_default: bool,
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `Address`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for Address {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &[
            "customer_id",
            "recipient_name",
            "city",
            "country",
            "is_default",
        ]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        &["country", "is_default"]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &["recipient_name", "city", "postal_code"]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["-id"]
    }
}
