//! Generated by `rustio-admin startapp cart_item`. Customise freely.

use rustio_admin::{ModelAdmin, RustioAdmin};

#[derive(RustioAdmin)]
pub struct CartItem {
    pub id: i64,
    pub customer_id: i64,
    pub product_id: i64,
    pub quantity: i32,
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `CartItem`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for CartItem {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &["id", "customer_id", "product_id", "quantity"]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        // Example: filter the list by a status enum.
        // &["status"]
        &[]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &[]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["-id"]
    }
}
