//! Generated by `rustio-admin startapp product_image`. Customise freely.

use rustio_admin::{ModelAdmin, RustioAdmin};

#[derive(RustioAdmin)]
pub struct ProductImage {
    pub id: i64,
    pub product_id: i64,
    pub url: String,
    pub alt_text: String,
    pub position: i32,
    pub is_primary: bool,
}

// The `ModelAdmin` impl below customises the admin list / form
// surface for `ProductImage`. Every method has a sensible default;
// these starter overrides reflect the fields you declared with
// `--field` at scaffold time. Edit freely.
impl ModelAdmin for ProductImage {
    /// Columns shown in the list-page table. Order matches the
    /// `--field` declaration order.
    fn list_display() -> &'static [&'static str] {
        &["product_id", "url", "position", "is_primary"]
    }

    /// Columns whose `=` value is filterable via `?filter_<col>=<v>`
    /// chips above the list page. Strings, enums, and small-cardinality
    /// columns make the most sense here.
    fn list_filter() -> &'static [&'static str] {
        &["is_primary"]
    }

    /// Columns that the list-page `?q=...` search box matches with
    /// `ILIKE`. Defaulted to the text-shaped fields you declared
    /// (`str` / `text`); leave empty if none.
    fn search_fields() -> &'static [&'static str] {
        &["alt_text"]
    }

    /// Default sort order. Prefix with `-` for descending.
    fn ordering() -> &'static [&'static str] {
        &["product_id", "position"]
    }
}
