-- Generated by `rustio-admin startapp translator`, then seeded with a few
-- example translators so the admin is non-empty on first run. Append-only:
-- to change the schema, add a new numbered file — don't edit this one.

CREATE TABLE translators (
    id BIGSERIAL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "languages" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO translators ("name", "email", "languages", "active") VALUES
    ('Amina Hassan',  'amina@agency.example',  'en, ar, sv', TRUE),
    ('Pierre Dubois', 'pierre@agency.example', 'fr, en',     TRUE),
    ('Sven Karlsson', 'sven@agency.example',   'sv, en',     FALSE);
