-- Generated by `rustio-admin startapp task`, then seeded with example jobs.
-- `status` is constrained by a CHECK to the same set the model declares in
-- #[rustio(choices = …)] — the admin renders it as a dropdown, Postgres
-- enforces it. `translator_id` is a foreign key rendered as a link.

CREATE TABLE tasks (
    id BIGSERIAL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "source_lang" TEXT NOT NULL,
    "target_lang" TEXT NOT NULL,
    "word_count" INTEGER NOT NULL,
    "deadline" DATE NOT NULL,
    "translator_id" BIGINT NOT NULL REFERENCES translators(id),
    "status" TEXT NOT NULL DEFAULT 'available'
        CHECK ("status" IN ('available', 'in_progress', 'review', 'completed', 'reassigned'))
);

CREATE INDEX tasks_status_idx     ON tasks ("status");
CREATE INDEX tasks_translator_idx ON tasks ("translator_id");

INSERT INTO tasks
    ("title", "source_lang", "target_lang", "word_count", "deadline", "translator_id", "status")
VALUES
    ('Medical discharge summary', 'en', 'ar', 1200, DATE '2026-07-10', 1, 'in_progress'),
    ('Rental contract',           'sv', 'en',  800, DATE '2026-07-08', 1, 'review'),
    ('Court hearing transcript',  'fr', 'en', 3400, DATE '2026-07-15', 2, 'available');
