[package]
name = "rustio-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Django Admin, but for Rust. A small, focused admin framework."
readme = "../../README.md"

[dependencies]
